- name: play level variables
  hosts: local
  connection: local
  vars:
    COURSE: DEVOPS
    TRAINER: SHIVA
    DURATION: 150 HRS
  tasks:
  - debug:
      msg: "I AM Learning {{ COUSRE }} with trainer is {{ TRAINER }} and TIME {{ DURATION }}"