- name: Play level variables
  hosts: localhost
  connection: local
  vars:
    COURSE: "DEVOPS"
    TRAINER: "SHIVA"
    DURATION: "150HRS"
  tasks:
  - debug:
      msg: "Hi, I am learning {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }}"