- name: install and start ngix
  hosts: frontend
  tasks:
  - name: install nginx
    ansible.bulitin.package:
      name: nginx
      state:present
  - name: start nginx
    service:
     name: nginx
     state: started
     enabled: yes