- name: demo on variables
  hosts: localhost
  connection: local
  var: 
    COURSE: "DEVOPS"
    TRAINER: "SHIVA KUMAR"
    DURATION: "150 HRS"
  tasks:
  - debug:
     -msg: "MY {{ COURSE }} TRAINER IS {{ TRAINER }} AND DURATION IS {{ DURATION }}"
